# Generated by Django 2.2.23 on 2021-05-22 15:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=2048, verbose_name='Описание')),
                ('site', models.CharField(blank=True, max_length=256, verbose_name='Сайт')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=2048, verbose_name='Описание')),
                ('wage_from', models.IntegerField(default=None, null=True)),
                ('wage_up_to', models.IntegerField(default=None, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('companie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Companie')),
            ],
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vacancy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Vacancy')),
            ],
        ),
    ]
