# Generated by Django 2.2.23 on 2021-05-22 22:57

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companie',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=companies.models.get_picture_path, verbose_name='Логотип'),
        ),
    ]
